// import { Provider } from 'react-redux';
// import { store } from '@/lib/store'; 

// import { sora } from './fonts';
// import './globals.css';

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body className={`${sora.variable} font-sans bg-black text-white`}>
//         <Provider store={store}>
//           {children}
//         </Provider>
//       </body>
//     </html>
//   );
// }















// app/layout.js
import { sora } from './fonts';
import './globals.css';
import { Providers } from './provider'; 

export const metadata = {
  title: "Sulio Art",
  description: "Sulio Art: Artist AI ChatBot, A collection of digital art and illustrations",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${sora.variable} font-sans bg-black text-white`}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}

